### PR TITLE
Minor template changes and .gitignore

### PR DESCRIPTION
**Pull request by am357**
*Issue #, if available:*

*Description of changes:*
Template changes:
1- Feature name -> Change name
2- PR Link

Adds `.gitignore`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by alancai98 — APPROVED** [review]
:shipit:

**Review by RCHowell — APPROVED** [review]

**Review by RCHowell — CHANGES_REQUESTED** [review]
`.DS_Store`?

**Comment by am357** [comment]
> `.DS_Store`?

Let me add it.

**Review by RCHowell — APPROVED** [review]

**Comment by am357** [comment]
> > `.DS_Store`?
> 
> Let me add it.

Done.

**Pull request merged**
